import * as path from "node:path";
import type {
  GeneratedPR,
  GeneratedPRFile,
  GitContext,
  PRExample,
  ResolvedGenMdConfig,
  PRGenerationOptions,
} from "../types/index.js";

const DEFAULT_PR_BODY_TEMPLATE = `## Summary

Generated by \`{{name}}\` using gen-md.

{{description}}

## Changes

- Updated \`{{output}}\`

## Cascade Chain

\`\`\`
{{cascade_chain}}
\`\`\`

{{#if recent_commits}}
## Recent Commits
{{recent_commits}}
{{/if}}

{{#if pr_examples}}
## Referenced PRs
{{pr_examples}}
{{/if}}

---
Generated with [gen-md](https://github.com/gen-md/gen-md)
`;

/**
 * PR generator from .gen.md files
 */
export class PRGenerator {
  private options: Required<PRGenerationOptions>;

  constructor(options: PRGenerationOptions = {}) {
    this.options = {
      title: options.title ?? "",
      base: options.base ?? "main",
      labels: options.labels ?? [],
      draft: options.draft ?? true,
    };
  }

  /**
   * Generate PR output from resolved config and generated content
   */
  generate(
    resolved: ResolvedGenMdConfig,
    generatedContent: string,
    gitContext: GitContext | null,
    prExamples: PRExample[]
  ): GeneratedPR {
    const outputPath = resolved.frontmatter.output || "output.md";
    const outputDir = path.dirname(
      resolved.chain[resolved.chain.length - 1].filePath
    );
    const fullOutputPath = path.resolve(outputDir, outputPath);

    // Determine title
    const title =
      this.options.title || this.inferTitle(resolved, generatedContent);

    // Generate PR body
    const body = this.generateBody(resolved, gitContext, prExamples);

    // Create file entry
    const file: GeneratedPRFile = {
      path: fullOutputPath,
      content: generatedContent,
      action: "create", // or "update" based on existence check
    };

    // Determine head branch name
    const head = this.generateBranchName(resolved);

    return {
      title,
      body,
      base: this.options.base,
      head,
      files: [file],
      labels: this.options.labels,
      sourcePath: resolved.chain[resolved.chain.length - 1].filePath,
    };
  }

  /**
   * Infer PR title from content
   */
  private inferTitle(
    resolved: ResolvedGenMdConfig,
    content: string
  ): string {
    const name = resolved.frontmatter.name || "generated";
    const output = resolved.frontmatter.output || "output";

    // Check first line of content for heading
    const firstLine = content.split("\n")[0];
    if (firstLine.startsWith("# ")) {
      return `docs: Update ${firstLine.substring(2).trim()}`;
    }

    return `docs: Update ${output} via ${name}`;
  }

  /**
   * Generate PR body from template
   */
  private generateBody(
    resolved: ResolvedGenMdConfig,
    gitContext: GitContext | null,
    prExamples: PRExample[]
  ): string {
    let body = DEFAULT_PR_BODY_TEMPLATE;

    // Replace placeholders
    body = body.replace("{{name}}", resolved.frontmatter.name || "gen-md");
    body = body.replace(
      "{{description}}",
      resolved.frontmatter.description || ""
    );
    body = body.replace("{{output}}", resolved.frontmatter.output || "");
    body = body.replace(
      "{{cascade_chain}}",
      resolved.chain.map((f) => f.filePath).join(" -> ")
    );

    if (gitContext && gitContext.commits.length > 0) {
      body = body.replace(
        "{{#if recent_commits}}\n{{recent_commits}}\n{{/if}}",
        gitContext.commits.map((c) => `- ${c.subject}`).join("\n")
      );
    } else {
      body = body.replace("{{#if recent_commits}}\n{{recent_commits}}\n{{/if}}", "");
    }

    if (prExamples.length > 0) {
      body = body.replace(
        "{{#if pr_examples}}\n{{pr_examples}}\n{{/if}}",
        prExamples.map((e) => `- #${e.prNumber}: ${e.prTitle}`).join("\n")
      );
    } else {
      body = body.replace("{{#if pr_examples}}\n{{pr_examples}}\n{{/if}}", "");
    }

    return body;
  }

  /**
   * Generate branch name
   */
  private generateBranchName(resolved: ResolvedGenMdConfig): string {
    const name = resolved.frontmatter.name || "gen-md";
    const timestamp = Date.now();
    return `gen-md/${name.replace(/[^a-z0-9-]/gi, "-")}-${timestamp}`;
  }
}

/**
 * Format GeneratedPR for gh CLI
 */
export function formatPRForGhCli(pr: GeneratedPR): string {
  const escapedBody = pr.body.replace(/"/g, '\\"').replace(/\n/g, "\\n");
  const args = [
    `gh pr create`,
    `--title "${pr.title}"`,
    `--body "${escapedBody}"`,
    `--base ${pr.base}`,
  ];

  if (pr.labels.length > 0) {
    args.push(`--label "${pr.labels.join(",")}"`);
  }

  return args.join(" \\\n  ");
}

/**
 * Factory function
 */
export function createPRGenerator(
  options?: PRGenerationOptions
): PRGenerator {
  return new PRGenerator(options);
}
